<?php

class Localization extends ModelFoodout
{

    /**
     *
     * @var integer
     * @Primary
     * @Identity
     * @Column(type="integer", length=11, nullable=false)
     */
    public $id;

    /**
     *
     * @var string
     * @Column(type="integer", length=11, nullable=false)
     */
    public $object_id;

    /**
     *
     * @var string
     * @Column(type="string", nullable=false, length=8)
     */
    public $locale;

    /**
     *
     * @var string
     * @Column(type="string", length = 32m nullable=false)
     */
    public $field;

    /**
     *
     * @var integer
     * @Column(type="string",  nullable=true)
     */
    public $content = null;

    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSource('city_localized');
    }


    public function setSource($source)
    {
        parent::setSource($source); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function getField()
    {
        return $this->field;
    }

    /**
     * @param string $field
     */
    public function setField($field)
    {
        $this->field = $field;
    }

    /**
     * @return int
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * @param int $content
     */
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * @return string
     */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
     * @param string $locale
     */
    public function setLocale($locale)
    {
        $this->locale = $locale;
    }

    /**
     * @return string
     */
    public function getObjectId()
    {
        return $this->object_id;
    }

    /**
     * @param string $object_id
     */
    public function setObjectId($object_id)
    {
        $this->object_id = $object_id;
    }
}
